# Generated by Django 6.0.3 on 2026-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='donation_images/'),
        ),
    ]
