# Generated by Django 6.0.4 on 2026-04-30 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation_app', '0003_donation_latitude_donation_longitude'),
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donation_app.donation')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register_app.donor')),
            ],
        ),
    ]
